### ISSUE TITLE
could you share the code of random transformer mentioned in the paper

### ISSUE THREAD

**Issue by unihe** [romilbert/samformer#12]
really interested about the implemention of it

**Comment by romilbert** [comment]
Thanks for your feedback. To use `random_transformer`, you can pass `transformer_random` as an argument to `--model`. This will automatically set the `trainable` argument of the transformer to `False` in the `initialize_model` function.

**Comment by unihe** [comment]
Thanks for rapdly relpy. Also, I wanna consult that **if all the parameters in attention layer are frozen** when use random_transformer since self.attention_layer.trainable = trainable (which is false in random_transformer) in the code I found.
