### ISSUE TITLE
Is this step function necessary? I didn't find any input for “closure”？

### ISSUE THREAD

**Issue by HuangZR-stu** [romilbert/samformer#14]
https://github.com/romilbert/samformer/blob/636e0c340902cd1adf2e964466a24b8d7657d2e9/samformer_pytorch/samformer/utils/sam.py#L58

When the second iteration occurs（optimizer.second_step(zero_grad=True), I run to line 49, self. base_optizer. step() # do the actual "sharpness aware" update; This function will be triggered, but there is no definition of closure, naturally triggering the error "Sharpeness Aware Minimization requires closure, but it was not provided". I commented it out and it can run, but is this part necessary? What is the function of this?

**Comment by ambroiseodt** [comment]
Thanks for your message.

The Sharpness Aware Minimization implementation we used is inspired from https://github.com/davda54/sam.
The .step method is a novel feature compared to the original implementation from https://arxiv.org/pdf/2010.01412 that enables to do directly the first_step and second_step and the closure is used to do an additional forward and backward pass as defined in https://github.com/davda54/sam: 'the closure should do an additional full forward and backward pass on the optimized model (default: None)'.

In our implementation, we do not make use of the step method but explicitly call .first_step and .second_step methods which explains why it still works after you commented it. For the sake of consistency, and potential future use, we will keep the .step method in the utils/sam.py implementation.

I hope this answers your questions. For more details, I invite you to look at https://github.com/davda54/sam that provides clear explanations on the new features.

Best,

Ambroise
