### ISSUE TITLE
Adding models to "Time Series Library"

### ISSUE THREAD

**Issue by rvandewater** [romilbert/samformer#16]
Hi,

Thanks for the great work! I suggest adding your model to https://github.com/thuml/Time-Series-Library. I am aware that this could be a considerable effort, but it would make it possible to benchmark/introduce your work more broadly. This is just a feature request from my side.

**Comment by ambroiseodt** [comment]
Thanks a lot for the comment and for the nice suggestion. This is indeed a very good idea, however, it seems that the models are all optimized with Adam in their library, while our approach combines a lightweight implementation with sharpness-aware minimization. Hence, integrating SAMformer in their pipeline does not seem straightforward as it would also require to update significantly their optimization framework.
