### ISSUE TITLE
 tensorflow-macos==2.13.0 (from versions: none)

### ISSUE THREAD

**Issue by Seham-Nasr** [romilbert/samformer#2]
ERROR: Could not find a version that satisfies the requirement tensorflow-macos==2.13.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-macos==2.13.0

**Comment by romilbert** [comment]
Thank you for raising this problem. The requirement `tensorflow-macos==2.13.0` has been removed from the requirements to simply use the standard version `2.13.0` of TensorFlow. The code has been updated accordingly and should now work on different operating systems. Please let us know if you encounter any further issues.
