### ISSUE TITLE
Training on time series datasets with different dimensions

### ISSUE THREAD

**Issue by kkiskkk** [romilbert/samformer#7]
If my data comes from different types of datasets, can I combine them into one data set for training? Will this affect the results? (The premise is that they are all time series with the same dimension)
Or is it better to train them separately multiple times?
Looking forward to your reply, thank you!

**Comment by kkiskkk** [comment]
In other words, is it possible to input sequences of different dimensions at the same time?

**Comment by romilbert** [comment]
Hi,

I designed SAMformer to handle inputs with the shape (batch_size, seq_len, _features). If you merge datasets with different seq_len, you can pad them with zeros to make all inputs the same length. Similarly, for different n_features, add artificial zero features.

However, I recommend training on separate datasets. In my experiments, merging ETTh1 and ETTh2 for testing on ETTh1 resulted in an MSE of 0.40, compared to 0.38 when trained on ETTh1 alone and tested on ETTh1.
Alternatively, you can train on a merged dataset and then fine-tune on a specific one for faster convergence.

Romain
